# Generated by Django 5.0.7 on 2025-09-20 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingTarget",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target funding amount to raise",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "pre_money_valuation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pre-money valuation of the startup",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "post_money_valuation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Post-money valuation (calculated)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "funding_round",
                    models.CharField(
                        choices=[
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("series_c", "Series C"),
                            ("series_d", "Series D"),
                            ("mezzanine", "Mezzanine"),
                            ("ipo", "IPO"),
                        ],
                        help_text="Current funding round",
                        max_length=50,
                    ),
                ),
                (
                    "use_of_funds",
                    models.TextField(blank=True, help_text="How the funding will be used"),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True, help_text="Timeline for raising the funds", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this funding target is currently active"
                    ),
                ),
                (
                    "startup",
                    models.OneToOneField(
                        help_text="The startup this funding target belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_target",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Target",
                "verbose_name_plural": "Funding Targets",
                "db_table": "funding_target",
                "indexes": [
                    models.Index(fields=["startup"], name="funding_tar_startup_52da62_idx"),
                    models.Index(fields=["funding_round"], name="funding_tar_funding_6d4779_idx"),
                    models.Index(fields=["is_active"], name="funding_tar_is_acti_503f7a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaisedFund",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "amount_raised",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount of funds raised", max_digits=15
                    ),
                ),
                (
                    "funding_round",
                    models.CharField(
                        choices=[
                            ("pre_seed", "Pre-Seed"),
                            ("seed", "Seed"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("series_c", "Series C"),
                            ("series_d", "Series D"),
                            ("mezzanine", "Mezzanine"),
                            ("ipo", "IPO"),
                            ("debt", "Debt Financing"),
                            ("grant", "Grant"),
                            ("other", "Other"),
                        ],
                        help_text="Funding round type",
                        max_length=50,
                    ),
                ),
                ("funding_date", models.DateField(help_text="Date when the funding was raised")),
                (
                    "lead_investor",
                    models.CharField(
                        blank=True, help_text="Name of the lead investor", max_length=255
                    ),
                ),
                (
                    "participating_investors",
                    models.TextField(blank=True, help_text="List of all participating investors"),
                ),
                (
                    "pre_money_valuation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pre-money valuation at the time of funding",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "post_money_valuation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Post-money valuation after funding",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "equity_offered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of equity offered in this round",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "use_of_funds",
                    models.TextField(blank=True, help_text="How the raised funds will be used"),
                ),
                (
                    "is_announced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this funding round has been publicly announced",
                    ),
                ),
                (
                    "announcement_date",
                    models.DateField(
                        blank=True, help_text="Date when the funding was announced", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about the funding round"
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup that raised these funds",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raised_funds",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raised Fund",
                "verbose_name_plural": "Raised Funds",
                "db_table": "raised_fund",
                "ordering": ["-funding_date", "-amount_raised"],
                "indexes": [
                    models.Index(fields=["startup"], name="raised_fund_startup_870f9b_idx"),
                    models.Index(fields=["funding_round"], name="raised_fund_funding_9e5bdb_idx"),
                    models.Index(fields=["funding_date"], name="raised_fund_funding_340922_idx"),
                    models.Index(fields=["is_announced"], name="raised_fund_is_anno_36a4c9_idx"),
                ],
            },
        ),
    ]
