# Generated by Django 5.2.18 on 2026-10-07 21:56

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80)),
                ("idea", models.CharField(blank=True, max_length=280)),
                (
                    "repo_full_name",
                    models.CharField(
                        blank=True, help_text="GitHub 'owner/repo'", max_length=140
                    ),
                ),
                ("live_url", models.URLField(blank=True, max_length=300)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("unlisted", "Unlisted"), ("public", "Public")],
                        default="unlisted",
                        max_length=10,
                    ),
                ),
                (
                    "ownership_token",
                    models.CharField(
                        default=apps.projects.models.new_ownership_token,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "slug"), name="uniq_project_slug_per_user"
                    )
                ],
            },
        ),
    ]
