# Generated by Django 5.2.18 on 2026-10-08 13:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def verify_existing_accounts(apps, schema_editor):
    # Every account so far was created through an emailed link (or the seeder),
    # so its owner has already proven the inbox.
    User = apps.get_model("accounts", "User")
    User.objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=django.utils.timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("sign_in", "Sign in"),
                    ("password_reset", "Password reset"),
                    ("verify_email", "Verify email"),
                ],
                default="sign_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=20)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="SignInEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sign_in", "Signed in"),
                            ("sign_in_failed", "Sign-in failed"),
                            ("locked", "Too many attempts"),
                            ("signed_up", "Signed up"),
                            ("signed_out", "Signed out"),
                            ("password_reset", "Password reset"),
                            ("password_changed", "Password changed"),
                            ("email_verified", "Email verified"),
                            ("session_revoked", "Session revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=20)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_in_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub"), ("google", "Google")],
                        max_length=20,
                    ),
                ),
                ("uid", models.CharField(max_length=191)),
                (
                    "login",
                    models.CharField(
                        blank=True, help_text="Username or email there", max_length=191
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "uid"), name="uniq_social_identity"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="one_identity_per_provider"
                    ),
                ],
            },
        ),
        migrations.RunPython(verify_existing_accounts, migrations.RunPython.noop),
    ]
