# Generated by Django 5.0.7 on 2025-09-20 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueModel",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the revenue model", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of how this revenue model works"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying models (lower numbers first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this revenue model is currently available for selection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Model",
                "verbose_name_plural": "Revenue Models",
                "db_table": "revenue_model",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["order"], name="revenue_mod_order_3e348d_idx"),
                    models.Index(fields=["is_active"], name="revenue_mod_is_acti_5ed438_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueStream",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                ("name", models.CharField(help_text="Name of the revenue stream", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the revenue stream"),
                ),
                (
                    "monthly_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly revenue from this stream",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual revenue from this stream",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "revenue_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total revenue from this stream",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Whether this is a recurring revenue stream"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this revenue stream is currently active"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="When this revenue stream started", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this revenue stream ended (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this revenue stream belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_streams",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Stream",
                "verbose_name_plural": "Revenue Streams",
                "db_table": "revenue_stream",
                "ordering": ["-revenue_percentage", "name"],
                "indexes": [
                    models.Index(fields=["startup"], name="revenue_str_startup_733a4e_idx"),
                    models.Index(fields=["is_recurring"], name="revenue_str_is_recu_1b73d4_idx"),
                    models.Index(fields=["is_active"], name="revenue_str_is_acti_104172_idx"),
                    models.Index(fields=["start_date"], name="revenue_str_start_d_1d5e0f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StartupRevenueModel",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary revenue model"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of revenue from this model",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about how this model is implemented",
                    ),
                ),
                (
                    "revenue_model",
                    models.ForeignKey(
                        help_text="The revenue model used by the startup",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="revenue.revenuemodel",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this revenue model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_models",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup Revenue Model",
                "verbose_name_plural": "Startup Revenue Models",
                "db_table": "startup_revenue_model",
                "ordering": ["-is_primary", "revenue_model__order"],
                "indexes": [
                    models.Index(fields=["startup"], name="startup_rev_startup_54a3ad_idx"),
                    models.Index(fields=["revenue_model"], name="startup_rev_revenue_d8f03b_idx"),
                    models.Index(fields=["is_primary"], name="startup_rev_is_prim_67f403_idx"),
                ],
                "unique_together": {("startup", "revenue_model")},
            },
        ),
    ]
