# Generated by Django 4.2.24 on 2025-09-05 13:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeZone",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "_id",
                    models.IntegerField(
                        db_index=True, editable=False, null=True, unique=True
                    ),
                ),
                ("zone_name", models.CharField(max_length=150, unique=True)),
                ("gmt_offset", models.IntegerField(blank=True, null=True)),
                (
                    "gmt_offset_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tz_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Time Zone",
                "verbose_name_plural": "Time Zones",
                "ordering": ["zone_name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "_id",
                    models.IntegerField(
                        db_index=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "iso3",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-3 code",
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "iso2",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 code",
                        max_length=2,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 numeric code",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        help_text="International calling code",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("capital", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Currency code (e.g., USD)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "currency_symbol",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "tld",
                    models.CharField(
                        blank=True,
                        help_text="Top-level domain",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "native",
                    models.CharField(
                        blank=True, help_text="Native name", max_length=255, null=True
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("subregion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Latitude coordinate",
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Longitude coordinate",
                        max_digits=11,
                        null=True,
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this country is active for selection",
                    ),
                ),
                (
                    "timezones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Timezones available in this country",
                        related_name="countries",
                        to="countries.timezone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="countries_c_name_67e711_idx"),
                    models.Index(fields=["iso2"], name="countries_c_iso2_7f7a08_idx"),
                    models.Index(fields=["iso3"], name="countries_c_iso3_3ba5ad_idx"),
                    models.Index(
                        fields=["region"], name="countries_c_region_927116_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="countries_c_is_acti_30a73f_idx"
                    ),
                ],
            },
        ),
    ]
