# Generated by Django 4.2.30 on 2026-10-07 21:35

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80)),
                ("idea", models.CharField(blank=True, max_length=280)),
                (
                    "repo_full_name",
                    models.CharField(blank=True, help_text="GitHub 'owner/repo'", max_length=140),
                ),
                ("live_url", models.URLField(blank=True, max_length=300)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("unlisted", "Unlisted"), ("public", "Public")],
                        default="unlisted",
                        max_length=10,
                    ),
                ),
                (
                    "ownership_token",
                    models.CharField(
                        default=apps.projects.models.new_ownership_token,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="uniq_project_slug_per_user"
            ),
        ),
    ]
