# Generated by Django 5.2.18 on 2026-10-07 21:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="PathVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("outcome", models.CharField(blank=True, max_length=300)),
                ("content_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="learning.path",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("shipped", "Shipped"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2-4", "2–4 hours a week"),
                            ("5-8", "5–8 hours a week"),
                            ("10+", "10+ hours a week"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "path_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="learning.pathversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        help_text="The team role this station teaches", max_length=80
                    ),
                ),
                (
                    "path_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="learning.pathversion",
                    ),
                ),
            ],
            options={
                "ordering": ["path_version", "order"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("learn", "Learn"),
                            ("build", "Build"),
                            ("check", "Check"),
                            ("ship", "Ship"),
                        ],
                        max_length=10,
                    ),
                ),
                ("est_minutes", models.PositiveSmallIntegerField()),
                ("requires_laptop", models.BooleanField(default=False)),
                ("body_md", models.TextField(blank=True)),
                (
                    "check_spec",
                    models.JSONField(
                        blank=True,
                        help_text="Declarative verification spec. Steps with a check can only be completed by a passing CheckRun.",
                        null=True,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="learning.station",
                    ),
                ),
            ],
            options={
                "ordering": ["station__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="StepProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("available", "Available"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="locked",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_position", models.PositiveIntegerField(default=0)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress",
                        to="learning.step",
                    ),
                ),
            ],
            options={
                "ordering": ["step__station__order", "step__order"],
            },
        ),
        migrations.AddConstraint(
            model_name="pathversion",
            constraint=models.UniqueConstraint(
                fields=("path", "version"), name="uniq_path_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="one_active_enrollment_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("path_version", "order"), name="uniq_station_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("path_version", "slug"), name="uniq_station_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                fields=("station", "order"), name="uniq_step_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="stepprogress",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "step"), name="uniq_progress_step"
            ),
        ),
    ]
