# Generated by Django 5.2.18 on 2026-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never deployed anything"),
                    ("once", "Deployed once or twice"),
                    ("often", "Deploys often"),
                ],
                max_length=6,
            ),
        ),
    ]
