# Generated by Django 4.2.24 on 2025-09-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("r", "read"), ("u", "unread"), ("s", "snoozed")],
                        default="u",
                        max_length=1,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("mention", "Mention"),
                            ("reply", "Reply"),
                            ("reaction", "Reaction"),
                            ("follow", "Follow"),
                            ("message", "Direct Message"),
                            ("system", "System"),
                            ("moderation", "Moderation"),
                            ("achievement", "Achievement"),
                            ("event", "Event"),
                            ("live_update", "Live Update"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("action_url", models.URLField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("snooze_until", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_7088ed_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "created"],
                        name="notificatio_notific_703930_idx",
                    ),
                    models.Index(
                        fields=["priority", "created"],
                        name="notificatio_priorit_62e221_idx",
                    ),
                ],
            },
        ),
    ]
