"""
Celery settings for the project.
"""

import os
from ..config_loader import get_celery_config, get_environment
from .cron import CELERY_BEAT_SCHEDULE as CRON_SCHEDULE, CELERY_BEAT_SCHEDULER, CELERY_BEAT_SCHEDULE_FILENAME


env = get_environment()

pytest_running = (
    "pytest" in os.environ.get("_", "") 
    or os.environ.get("PYTEST_CURRENT_TEST")
    or "DJANGO_SETTINGS_MODULE" in os.environ 
    and "testing" in os.environ.get("DJANGO_SETTINGS_MODULE", "")
)
if (
    env == "testing" 
    or os.environ.get("TESTING") == "true" 
    or pytest_running
    or os.environ.get("CELERY_TASK_ALWAYS_EAGER") == "True"
):

    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

    CELERY_ACCEPT_CONTENT = ["application/json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = "UTC"
    CELERY_TASK_TRACK_STARTED = True
    CELERY_TASK_TIME_LIMIT = 3600
    CELERY_TASK_SOFT_TIME_LIMIT = 6000
    CELERY_WORKER_DISABLE_RATE_LIMITS = True
    CELERY_WORKER_PREFETCH_MULTIPLIER = 1
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
    CELERY_WORKER_CONCURRENCY = 1
    CELERY_WORKER_STATE_DB = "/tmp/celery_worker_state_test"
    CELERY_WORKER_MAX_MEMORY_PER_CHILD = 262144

    CELERY_TASK_IGNORE_RESULT = False
    CELERY_RESULT_EXPIRES = 300
    CELERY_TASK_REJECT_ON_WORKER_LOST = True
    CELERY_BROKER_CONNECTION_RETRY = False
    CELERY_BROKER_CONNECTION_RETRY_DELAY = 0
    CELERY_RESULT_BACKEND_CONNECTION_RETRY = False
    CELERY_WORKER_DB_CONNECTION_MAX_AGE = 0
    CELERY_TASK_ACKS_LATE = False
    CELERY_BROKER_POOL_LIMIT = 1
    CELERY_BROKER_CONNECTION_TIMEOUT = 1.0
    CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {}
    CELERY_BEAT_SCHEDULE = CRON_SCHEDULE
    CELERY_BEAT_SCHEDULER = CELERY_BEAT_SCHEDULER
    CELERY_BEAT_SCHEDULE_FILENAME = CELERY_BEAT_SCHEDULE_FILENAME

else:

    celery_config = get_celery_config()
    CELERY_BROKER_URL = celery_config["BROKER_URL"]
    CELERY_RESULT_BACKEND = celery_config["RESULT_BACKEND"]

    CELERY_ACCEPT_CONTENT = ["application/json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = celery_config["TIMEZONE"]
    CELERY_TASK_TRACK_STARTED = celery_config["TASK_TRACK_STARTED"]
    CELERY_TASK_TIME_LIMIT = celery_config["TASK_TIME_LIMIT"]
    CELERY_TASK_SOFT_TIME_LIMIT = celery_config.get("TASK_SOFT_TIME_LIMIT", 6000)
    CELERY_WORKER_DISABLE_RATE_LIMITS = celery_config["WORKER_DISABLE_RATE_LIMITS"]
    CELERY_WORKER_PREFETCH_MULTIPLIER = celery_config["WORKER_PREFETCH_MULTIPLIER"]
    CELERY_WORKER_MAX_TASKS_PER_CHILD = celery_config["WORKER_MAX_TASKS_PER_CHILD"]
    CELERY_WORKER_CONCURRENCY = celery_config["WORKER_CONCURRENCY"]
    CELERY_WORKER_STATE_DB = celery_config["WORKER_STATE_DB"]
    CELERY_WORKER_MAX_MEMORY_PER_CHILD = celery_config.get(
        "WORKER_MAX_MEMORY_PER_CHILD", 8589934592
    )

    CELERY_TASK_IGNORE_RESULT = False
    CELERY_RESULT_EXPIRES = 3600
    CELERY_TASK_REJECT_ON_WORKER_LOST = True
    CELERY_BROKER_CONNECTION_RETRY = True
    CELERY_BROKER_CONNECTION_RETRY_DELAY = 1.0
    CELERY_RESULT_BACKEND_CONNECTION_RETRY = True
    CELERY_WORKER_DB_CONNECTION_MAX_AGE = 300
    CELERY_TASK_ACKS_LATE = True
    CELERY_BROKER_POOL_LIMIT = 10
    CELERY_BROKER_CONNECTION_TIMEOUT = 10.0
    CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
        "socket_keepalive": True,
        "socket_keepalive_options": {
            "TCP_KEEPIDLE": 1,
            "TCP_KEEPINTVL": 3,
            "TCP_KEEPCNT": 5,
        },
    }
    CELERY_BEAT_SCHEDULE = CRON_SCHEDULE
    CELERY_BEAT_SCHEDULER = CELERY_BEAT_SCHEDULER
    CELERY_BEAT_SCHEDULE_FILENAME = CELERY_BEAT_SCHEDULE_FILENAME

    CELERY_DEV = {
        "CELERY_TASK_ALWAYS_EAGER": celery_config["TASK_ALWAYS_EAGER"],
        "CELERY_TASK_EAGER_PROPAGATES": celery_config["TASK_EAGER_PROPAGATES"],
    }

    CELERY_PROD = {
        "CELERY_TASK_ALWAYS_EAGER": celery_config["TASK_ALWAYS_EAGER"],
        "CELERY_BROKER_URL": CELERY_BROKER_URL,
        "CELERY_RESULT_BACKEND": CELERY_RESULT_BACKEND,
        "CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP": True,
        "CELERY_BROKER_CONNECTION_MAX_RETRIES": 10,
        "CELERY_BROKER_CONNECTION_RETRY": True,
        "CELERY_BROKER_CONNECTION_RETRY_DELAY": 1.0,
        "CELERY_RESULT_BACKEND_CONNECTION_RETRY": True,
        "CELERY_TASK_REJECT_ON_WORKER_LOST": True,
        "CELERY_TASK_IGNORE_RESULT": False,
        "CELERY_RESULT_EXPIRES": 3600,
        "CELERY_WORKER_PREFETCH_MULTIPLIER": 1,
        "CELERY_WORKER_MAX_MEMORY_PER_CHILD": 8589934592,
    }


CELERY_TEST = {
    "CELERY_TASK_ALWAYS_EAGER": True,
    "CELERY_TASK_EAGER_PROPAGATES": True,
    "BROKER_BACKEND": "memory",
}
