# Generated by Django 5.0.7 on 2025-09-20 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "competitor_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("gcc", "GCC (Gulf Cooperation Council)"),
                            ("global", "Global"),
                        ],
                        help_text="Type of competitor (Local, GCC, or Global)",
                        max_length=10,
                    ),
                ),
                (
                    "competitor_name",
                    models.CharField(help_text="Name of the competitor company", max_length=255),
                ),
                (
                    "competitor_url",
                    models.URLField(blank=True, help_text="Competitor's website URL", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the competitor and their business"
                    ),
                ),
                (
                    "market_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated market share percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "funding_raised",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total funding raised by competitor",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year the competitor was founded", null=True
                    ),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of employees", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Competitor's headquarters location", max_length=255
                    ),
                ),
                ("strengths", models.TextField(blank=True, help_text="Competitor's key strengths")),
                (
                    "weaknesses",
                    models.TextField(blank=True, help_text="Competitor's weaknesses or gaps"),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        help_text="Level of competitive threat",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this competitor is still active"
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this competitor is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor",
                "verbose_name_plural": "Competitors",
                "db_table": "competitor",
                "ordering": ["-threat_level", "competitor_type", "competitor_name"],
                "indexes": [
                    models.Index(fields=["startup"], name="competitor_startup_7e4f4e_idx"),
                    models.Index(fields=["competitor_type"], name="competitor_competi_b1b642_idx"),
                    models.Index(fields=["threat_level"], name="competitor_threat__234d98_idx"),
                    models.Index(fields=["is_active"], name="competitor_is_acti_55c856_idx"),
                ],
            },
        ),
    ]
