version: "3.8"

services:
  kolct_ollama:
    environment:
      - OLLAMA_HOST=0.0.0.0

      - OLLAMA_USE_METAL=true

  kolct_backend:
    environment:
      - OLLAMA_GPU_ENABLED=true
      - OLLAMA_USE_METAL=true
    mem_limit: 8g
    cpus: 4.0

  kolct_ollama_webui:
    environment:
      - OLLAMA_GPU_ENABLED=true
      - OLLAMA_USE_METAL=true
