# Generated by Django 5.0.7 on 2025-09-20 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "person_company_name",
                    models.CharField(
                        help_text="Name of the person or company making the investment",
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Address of the investor")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254, null=True
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20, null=True
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Investor's website URL", null=True),
                ),
                (
                    "equity_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of equity received",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("angel", "Angel Investment"),
                            ("seed", "Seed Funding"),
                            ("series_a", "Series A"),
                            ("series_b", "Series B"),
                            ("series_c", "Series C"),
                            ("series_d", "Series D"),
                            ("mezzanine", "Mezzanine"),
                            ("ipo", "IPO"),
                            ("debt", "Debt Financing"),
                            ("grant", "Grant"),
                            ("other", "Other"),
                        ],
                        help_text="Type of investment made",
                        max_length=20,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount invested",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "investment_date",
                    models.DateField(blank=True, help_text="Date of investment", null=True),
                ),
                (
                    "is_lead_investor",
                    models.BooleanField(
                        default=False, help_text="Whether this investor is the lead investor"
                    ),
                ),
                (
                    "board_seat",
                    models.BooleanField(
                        default=False, help_text="Whether this investor has a board seat"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Additional notes about the investor"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this investment is currently active"
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this investor is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investors",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investor",
                "verbose_name_plural": "Investors",
                "db_table": "investor",
                "ordering": ["-investment_date", "-investment_amount", "person_company_name"],
                "indexes": [
                    models.Index(fields=["startup"], name="investor_startup_5d257d_idx"),
                    models.Index(fields=["investment_type"], name="investor_investm_0d0b85_idx"),
                    models.Index(fields=["investment_date"], name="investor_investm_6b5bd6_idx"),
                    models.Index(fields=["is_lead_investor"], name="investor_is_lead_34b920_idx"),
                    models.Index(fields=["is_active"], name="investor_is_acti_4079ff_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "full_name",
                    models.CharField(help_text="Full name of the stakeholder", max_length=255),
                ),
                (
                    "stakeholder_type",
                    models.CharField(
                        choices=[
                            ("investor", "Investor"),
                            ("advisor", "Advisor"),
                            ("partner", "Partner"),
                            ("supplier", "Supplier"),
                            ("member", "Member"),
                            ("customer", "Customer"),
                            ("vendor", "Vendor"),
                            ("other", "Other"),
                        ],
                        help_text="Type of stakeholder",
                        max_length=20,
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        help_text="Role or title in relation to the startup", max_length=255
                    ),
                ),
                (
                    "influence_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        help_text="How influential they are in the startup",
                        max_length=10,
                    ),
                ),
                (
                    "stake_interest_level",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        help_text="Their stake/interest level in the startup",
                        max_length=10,
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of ownership or shares (if investor/partner)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount invested (if applicable)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254, null=True
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20, null=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company name (if stakeholder represents a company)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes about the stakeholder",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this stakeholder relationship is currently active",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this stakeholder is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stakeholder",
                "verbose_name_plural": "Stakeholders",
                "db_table": "stakeholder",
                "ordering": ["-influence_level", "stakeholder_type", "full_name"],
                "indexes": [
                    models.Index(fields=["startup"], name="stakeholder_startup_0549c7_idx"),
                    models.Index(
                        fields=["stakeholder_type"], name="stakeholder_stakeho_368947_idx"
                    ),
                    models.Index(fields=["influence_level"], name="stakeholder_influen_2836e0_idx"),
                    models.Index(
                        fields=["stake_interest_level"], name="stakeholder_stake_i_d49f0f_idx"
                    ),
                    models.Index(fields=["is_active"], name="stakeholder_is_acti_1a7d5b_idx"),
                ],
            },
        ),
    ]
