# Generated by Django 4.2.24 on 2025-09-22 09:24

import apps.accounts.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                ("username", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the user account is active"
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user is verified (blue check mark for influencers)",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.accounts.user.models.user_directory_path,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("is_phone_verified", models.BooleanField(default=False)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="User's date of birth", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        help_text="User's gender",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("service", "Service"),
                            ("influencer", "Influencer"),
                            ("manufacturer", "Manufacturer"),
                            ("collector", "Collector"),
                            ("issuer", "Issuer"),
                            ("salesman", "Salesman"),
                            ("card_creator", "Card Creator"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the user is temporarily banned from logging in",
                    ),
                ),
                (
                    "ban_reason",
                    models.TextField(
                        blank=True, help_text="Reason for banning the user", null=True
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the user was banned", null=True
                    ),
                ),
                (
                    "ban_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ban expires (null for permanent ban)",
                        null=True,
                    ),
                ),
                (
                    "is_deactivated",
                    models.BooleanField(
                        default=False, help_text="Whether the user account is deactivated"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the user account was deactivated", null=True
                    ),
                ),
                (
                    "deactivation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for account deactivation", null=True
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who banned this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="countries.country",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "_user_user",
                "permissions": [
                    ("can_manage_user_roles", "Can manage user roles"),
                    ("can_view_admin_stats", "Can view admin statistics"),
                    ("can_moderate_all_content", "Can moderate all forum content"),
                    ("can_access_api", "Can access API endpoints"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                ("code", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                ("token", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "User Token",
                "verbose_name_plural": "User Tokens",
                "indexes": [models.Index(fields=["token"], name="user_userto_token_298935_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="Duser_user_email_2817fd_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="Duser_user_usernam_46726c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="Duser_user_role_96ecd5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created"], name="Duser_user_created_d1f048_idx"),
        ),
    ]
