# Generated by Django 4.2.24 on 2025-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("service", "Service"),
                ],
                db_index=True,
                default="user",
                max_length=20,
            ),
        ),
    ]
