# Generated by Django 5.0.7 on 2025-09-20 19:14

import apps.accounts.founder.models.founder_profile
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "full_name",
                    models.CharField(help_text="Full name of the founder", max_length=255),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Primary email address for business communications",
                        max_length=254,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ceo", "CEO - Chief Executive Officer"),
                            ("cto", "CTO - Chief Technology Officer"),
                            ("cmo", "CMO - Chief Marketing Officer"),
                            ("cfo", "CFO - Chief Financial Officer"),
                            ("coo", "COO - Chief Operating Officer"),
                            ("cpo", "CPO - Chief Product Officer"),
                            ("cso", "CSO - Chief Strategy Officer"),
                            ("founder", "Founder"),
                            ("co_founder", "Co-Founder"),
                            ("other", "Other"),
                        ],
                        help_text="Role/position in the startup",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(help_text="Base city or location", max_length=255)),
                ("birthdate", models.DateField(blank=True, help_text="Date of birth", null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter profile URL", null=True),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook profile URL", null=True),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL", null=True),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL", null=True),
                ),
                (
                    "personal_website",
                    models.URLField(blank=True, help_text="Personal website URL", null=True),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Founder's biography and background"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Founder's profile picture",
                        null=True,
                        upload_to=apps.accounts.founder.models.founder_profile.founder_avatar_path,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Background image for founder profile",
                        null=True,
                        upload_to=apps.accounts.founder.models.founder_profile.founder_background_path,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether this founder profile is verified"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether this profile is publicly visible"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account associated with this founder profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founder_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Founder Profile",
                "verbose_name_plural": "Founder Profiles",
                "db_table": "founder_profile",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "institution_name",
                    models.CharField(
                        help_text="Name of the educational institution", max_length=255
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="Degree obtained (e.g., Bachelor of Science, MBA, PhD)",
                        max_length=255,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, help_text="Field of study or major", max_length=255
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Start date of education", null=True),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date or graduation date", null=True
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="Whether currently enrolled"),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grade Point Average if applicable",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about the education"
                    ),
                ),
                (
                    "institution_website",
                    models.URLField(blank=True, help_text="Institution's website URL", null=True),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        help_text="The founder this education record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_history",
                        to="founder.founderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education Records",
                "db_table": "founder_education",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PreviousCompany",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "company_name",
                    models.CharField(help_text="Name of the company or startup", max_length=255),
                ),
                (
                    "profile_link",
                    models.URLField(
                        blank=True, help_text="Link to company profile or website", null=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Position or role held at the company", max_length=255
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Start date of employment", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="End date of employment", null=True),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Whether currently working at this company"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of role and achievements"),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("startup", "Startup"),
                            ("corporation", "Corporation"),
                            ("non_profit", "Non-Profit"),
                            ("government", "Government"),
                            ("consulting", "Consulting"),
                            ("other", "Other"),
                        ],
                        default="startup",
                        help_text="Type of company",
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry or sector of the company", max_length=100
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1000+", "1000+ employees"),
                        ],
                        help_text="Size of the company",
                        max_length=20,
                    ),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        help_text="The founder this company record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_companies",
                        to="founder.founderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Company",
                "verbose_name_plural": "Previous Companies",
                "db_table": "founder_previous_company",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="founderprofile",
            index=models.Index(fields=["user"], name="founder_pro_user_id_e8aeaa_idx"),
        ),
        migrations.AddIndex(
            model_name="founderprofile",
            index=models.Index(fields=["role"], name="founder_pro_role_e276a6_idx"),
        ),
        migrations.AddIndex(
            model_name="founderprofile",
            index=models.Index(fields=["location"], name="founder_pro_locatio_b77698_idx"),
        ),
        migrations.AddIndex(
            model_name="founderprofile",
            index=models.Index(fields=["is_verified"], name="founder_pro_is_veri_3aba37_idx"),
        ),
        migrations.AddIndex(
            model_name="founderprofile",
            index=models.Index(fields=["is_public"], name="founder_pro_is_publ_89c2f5_idx"),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(fields=["founder"], name="founder_edu_founder_e279cc_idx"),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(fields=["institution_name"], name="founder_edu_institu_0210bd_idx"),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(fields=["degree"], name="founder_edu_degree_83b5e9_idx"),
        ),
        migrations.AddIndex(
            model_name="previouscompany",
            index=models.Index(fields=["founder"], name="founder_pre_founder_6b03a2_idx"),
        ),
        migrations.AddIndex(
            model_name="previouscompany",
            index=models.Index(fields=["company_name"], name="founder_pre_company_6d6f2d_idx"),
        ),
        migrations.AddIndex(
            model_name="previouscompany",
            index=models.Index(fields=["company_type"], name="founder_pre_company_f779c7_idx"),
        ),
        migrations.AddIndex(
            model_name="previouscompany",
            index=models.Index(fields=["industry"], name="founder_pre_industr_9fe21b_idx"),
        ),
    ]
