# Generated by Django 5.0.7 on 2025-09-20 19:14

import apps.company.models.startup_profile
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentStage",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the development stage", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this stage represents"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying stages (lower numbers first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this stage is currently available for selection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Development Stage",
                "verbose_name_plural": "Development Stages",
                "db_table": "development_stage",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["order"], name="development_order_5f3bb6_idx"),
                    models.Index(fields=["is_active"], name="development_is_acti_d32fe0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StartupProfile",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "startup_name",
                    models.CharField(help_text="Name of the startup/company", max_length=255),
                ),
                (
                    "startup_industry",
                    models.CharField(help_text="Industry or sector of the startup", max_length=100),
                ),
                (
                    "website_link",
                    models.URLField(blank=True, help_text="Company website URL", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Headquarters location or remote status", max_length=255
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(help_text="Year the company was founded"),
                ),
                ("bio", models.TextField(blank=True, help_text="Company description and mission")),
                (
                    "services_and_products",
                    models.TextField(
                        blank=True, help_text="Description of services and products offered"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="Company LinkedIn page URL", null=True),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Company Twitter profile URL", null=True),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Company Facebook page URL", null=True),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Company Instagram profile URL", null=True
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, help_text="Company YouTube channel URL", null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo",
                        null=True,
                        upload_to=apps.company.models.startup_profile.startup_logo_path,
                    ),
                ),
                (
                    "pitch_deck_link",
                    models.URLField(
                        blank=True, help_text="Link to pitch deck presentation", null=True
                    ),
                ),
                (
                    "pitch_deck_file",
                    models.FileField(
                        blank=True,
                        help_text="Pitch deck file upload",
                        null=True,
                        upload_to=apps.company.models.startup_profile.startup_pitch_deck_path,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether this startup profile is verified"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether this profile is publicly visible"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the startup is currently active"
                    ),
                ),
                (
                    "primary_founder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary founder of the startup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_startups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup Profile",
                "verbose_name_plural": "Startup Profiles",
                "db_table": "startup_profile",
            },
        ),
        migrations.CreateModel(
            name="StartupDevelopmentStage",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "assigned_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this stage was assigned"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the stage assignment"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Current development stage of the startup",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.developmentstage",
                    ),
                ),
                (
                    "startup",
                    models.OneToOneField(
                        help_text="The startup this stage belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_stage",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup Development Stage",
                "verbose_name_plural": "Startup Development Stages",
                "db_table": "startup_development_stage",
            },
        ),
        migrations.CreateModel(
            name="CompanyMember",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("co_founder", "Co-Founder"),
                            ("employee", "Employee"),
                            ("advisor", "Advisor"),
                            ("consultant", "Consultant"),
                            ("intern", "Intern"),
                            ("contractor", "Contractor"),
                        ],
                        help_text="Type of membership in the company",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Position or role in the company", max_length=255),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Start date of membership", null=True),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date of membership (if applicable)", null=True
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Whether currently a member of the company"
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this member is the primary contact for the company",
                    ),
                ),
                (
                    "equity_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of equity owned (if applicable)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of role and responsibilities"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user account of this member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Member",
                "verbose_name_plural": "Company Members",
                "db_table": "company_member",
                "ordering": ["-is_current", "member_type", "position"],
            },
        ),
        migrations.CreateModel(
            name="TargetedMarket",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("gcc", "GCC (Gulf Cooperation Council)"),
                            ("global", "Global"),
                        ],
                        help_text="Type of market (Local, GCC, or Global)",
                        max_length=10,
                    ),
                ),
                (
                    "market_name",
                    models.CharField(
                        help_text="Name or description of the specific market", max_length=255
                    ),
                ),
                (
                    "market_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total market size in USD",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "market_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of market share targeted",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the market opportunity"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary target market"
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="The startup this market belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_markets",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Targeted Market",
                "verbose_name_plural": "Targeted Markets",
                "db_table": "targeted_market",
                "ordering": ["-is_primary", "market_type", "market_name"],
            },
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["startup_name"], name="startup_pro_startup_97b93b_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["startup_industry"], name="startup_pro_startup_c8fa06_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["founded_year"], name="startup_pro_founded_dadae3_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["location"], name="startup_pro_locatio_fe91af_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["is_verified"], name="startup_pro_is_veri_189086_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["is_public"], name="startup_pro_is_publ_40018e_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["is_active"], name="startup_pro_is_acti_dde3b1_idx"),
        ),
        migrations.AddIndex(
            model_name="startupdevelopmentstage",
            index=models.Index(fields=["startup"], name="startup_dev_startup_042fe8_idx"),
        ),
        migrations.AddIndex(
            model_name="startupdevelopmentstage",
            index=models.Index(fields=["stage"], name="startup_dev_stage_i_8b5f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="startupdevelopmentstage",
            index=models.Index(fields=["assigned_date"], name="startup_dev_assigne_81282a_idx"),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(fields=["startup"], name="company_mem_startup_dc9c75_idx"),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(fields=["user"], name="company_mem_user_id_53fa97_idx"),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(fields=["member_type"], name="company_mem_member__57f99b_idx"),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(fields=["is_current"], name="company_mem_is_curr_4914f5_idx"),
        ),
        migrations.AddIndex(
            model_name="companymember",
            index=models.Index(
                fields=["is_primary_contact"], name="company_mem_is_prim_6a86bc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companymember",
            unique_together={("startup", "user")},
        ),
        migrations.AddIndex(
            model_name="targetedmarket",
            index=models.Index(fields=["startup"], name="targeted_ma_startup_b5e9f1_idx"),
        ),
        migrations.AddIndex(
            model_name="targetedmarket",
            index=models.Index(fields=["market_type"], name="targeted_ma_market__920e51_idx"),
        ),
        migrations.AddIndex(
            model_name="targetedmarket",
            index=models.Index(fields=["is_primary"], name="targeted_ma_is_prim_b9a411_idx"),
        ),
    ]
