# Generated by Django 4.2.24 on 2025-09-23 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_fix_development_stage_enum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startupprofile",
            name="services_and_products",
        ),
        migrations.CreateModel(
            name="StartupServiceProduct",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_id", models.IntegerField(db_index=True, editable=False, null=True, unique=True)),
                ("name", models.CharField(help_text="Service/Product name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional description")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "startup",
                    models.ForeignKey(
                        help_text="Related startup profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_and_products",
                        to="company.startupprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup Service/Product",
                "verbose_name_plural": "Startup Services/Products",
                "db_table": "startup_service_product",
                "indexes": [
                    models.Index(
                        fields=["startup", "is_active"], name="startup_ser_startup_3b699a_idx"
                    ),
                    models.Index(fields=["name"], name="startup_ser_name_380637_idx"),
                ],
            },
        ),
    ]
